### PR TITLE
Automatically uncheck DB backup during quick setup

### PR DESCRIPTION
**Pull request by Molkobain**
As quick setup is mostly used on development / test / support environment, we want to uncheck the DB setup 95% of the time.
This PR aims at unchecking the DB backup automatically when using the quick setup.

Edit: The original code only works if you run the quick setup from the second page of the setup, not the first one.

### CODE REVIEW

**Comment by Hipska** [comment]
Did I miss something? What is the quick-setup?

**Comment by steffunky** [comment]
@Hipska Check ca99b0e

**Comment by Hipska** [comment]
Nice, will try it out. But hard to check code in a minified file 😞

**Comment by Molkobain** [comment]
IDK if you could get what the quick setup is from the commit Stephen gave, but basically it's a shortcut that fast-forward the setup steps. Pretty useful when you are doing upgrade often!

Unfortunately the file is minified as we use an "XSS vulnerability" to inject the JS snippet through the steps (current and next)

**Comment by piRGoif** [comment]
> @piRGoif can't be assigned to me as I'm the one asking for it 😁

This is what we usually do for internal PR : the dev who did the job is reponsible for getting feedbacks from the teams and update the PR accordingly O:)
This is surprising indeed but worked well with past PR ?

**Pull request closed without merging**
