### PR TITLE
💄 Update loading title

### PR DESCRIPTION
**Pull request by Hipska**
Added emoji warning sign: ⚠️ 

It can also be changed to an textual version instead: ⚠︎

### CODE REVIEW

**Comment by piRGoif** [comment]
Hello,
Out of curiosity in which browsers did you test this ?

**Comment by Hipska** [comment]
Safari, so all WebKit (Chrome,Edge,Opera) will behave similar..

**Comment by Molkobain** [comment]
Would be nice to test on Firefox as well as it is used by many developers. Otherwise, seems nice!

**Comment by Hipska** [comment]
This is on macOS with FF 52: 
image

**Comment by piRGoif** [comment]
Thanks for the feedback :)
Woa, Fx 52, you're not using it really often right ? :o) (current version Fx 87)

Seems ok to me, will discuss about this with the dev team :)

**Comment by Hipska** [comment]
Haha 😂 I knew I had to put a don't ask next to it. It's the last version that works for VPN software for a customer 😞

**Review by Molkobain — APPROVED** [review]

**Review by piRGoif — APPROVED** [review]

**Comment by piRGoif** [comment]
Considering this little change, and because there are 2 approvals, I'm merging this !

**Pull request merged**
